# Generated by Django 4.2.2 on 2023-06-16 11:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sonic_registration', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('file', models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(['mp3'])])),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('protected', 'Protected')], default='private', max_length=10)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sonic_registration.login')),
            ],
        ),
    ]
