# Generated by Django 4.2.2 on 2023-06-17 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sonic_registration', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
