# Generated by Django 4.2.2 on 2023-06-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sonic_registration', '0005_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='allowed_emails',
            field=models.TextField(blank=True),
        ),
    ]
